docs_dir:         "docs"
site_name:        "SFZ Instruments"
site_author:      "SFZ Instruments Organization"
site_url:         "https://sfzinstruments.github.io"
site_dir:         "_site"
site_description: "SFZ instruments website"
repo_name:        "GitHub"
repo_url:         "https://github.com/sfzinstruments/sfzinstruments.github.io"
edit_uri:         "edit/master/docs/"
remote_branch:    "www"
extra:
  site_since:      "2020"
  site_web_author: "SFZ Instruments Organization"
  repo_owner_url:  "https://github.com/sfzinstruments"
  repo_branch:     "master"
  cards:           "data/layout/cards.yml"
  nav:             "data/layout/navigation.yml"
# TODO: data for both documentation and layout (currently using macros plugin)?
  sfz_authors_layout:     "data/sfz/authors.yml"
  sfz_instruments_layout: "data/sfz/instruments.yml"
hooks:
- scripts/hooks.py
markdown_extensions:
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
    alt: short
    options:
      attributes:
        align: absmiddle
        height: 20px
        width: 20px
plugins:
  search: {}
  blogging:
    dirs:
    - news/posts
    locale: en
    full_content: true
    paging: true
    show_total: false
    size: 5
    template: "layout/blogging-plugin.html"
    meta_time_format: "%Y-%m-%dT%H:%M:%S%z"
    time_format: "%Y-%m-%d %H:%M:%S"
  exclude: # TODO: to remove when 1.5 comes out
    glob:
    - "*.j2"
  macros:
    include_yaml:
    - sfz_authors_macros:     "data/sfz/authors.yml"
    - sfz_instruments_macros: "data/sfz/instruments.yml"
    include_dir: "macros/includes"
    module_name: "macros/module"
    verbose: true
  gen-files:
    scripts:
    - scripts/generate_atom.py
theme:
  name:        null
  custom_dir: "layout"
  highlightjs: true
  hljs_light: "github"
  hljs_dark:  "github-dark-dimmed"
  nav_style:  "dark"
  locale:     "en"
  bootstrap_version: "5.3.0"
  favicons:
    apple_touch_icon_size: "152x152"
    msapp_tilecolor: "#da532c"
    theme_color: "#ffffff"
  shortcuts:
    help:     191 # ?
    next:      78 # n
    previous:  80 # p
    search:    83 # s
watch:
- data
- docs
- macros/includes
- layout
